Repository PPROF1-2021/a3-g8-teamfire, pull requests merged in 2021-10, with the labels that each got.

#10 subo mapa del sitio teamfire
  documentacion/Diagrama.jpg
Labels: documentation

#26 subo el cv modelo, la idea es que el usuario pueda editarlo, descarga…
  cv/css/menu.css
  cv/img/contacto.jpg
  cv/img/inserte foto.jpg
  cv/index.html
Labels: Back-end

#27 Revert "subo el cv modelo, la idea es que el usuario pueda editarlo, descarga…"
  cv/css/menu.css
  cv/img/contacto.jpg
  cv/img/inserte foto.jpg
  cv/index.html
Labels: Front-end

#28 subo los archivos del cv, la idea es que el usuario lo pueda editar, …
  frontend/csscv/menucv.css
  frontend/cvindex.html
  frontend/imgcv/contacto.jpg
  frontend/imgcv/inserte foto.jpg
Labels: Front-end
